### ISSUE TITLE
"Countdown" erased from FE

### ISSUE THREAD

**Issue by Neodammerung69** [Sandrem/FlyCasual#1235]
I play casually and really was looking forward to use "Countdown" in a squadron. Last version of the simulator he costed 44pts, and now it's been erased. That's how it'll stay, or is this a mistake?
![image](https://user-images.githubusercontent.com/43158903/45558643-03ed5480-b806-11e8-8cfc-271008ddcc67.png)

**Comment by Sandrem** [comment]
In 0.6.1 - a lot of SE cards where added.
"Countdown" by mistake was available in FE squadbuilder (but had all parameters from SE - this was a reason of wrong cost).
I just marked it as "SE only", as was planned.

Now we have situation, where some cards are present in SE content only, and can be present as FE content too, because ability is still the same. But this adaptation requires some work. I plan to return "Countdown" (and to make available few another SE cards in FE) in the next update.
