### ISSUE TITLE
Maybe known, but online games are crashing 

### ISSUE THREAD

**Issue by Werdna76** [Sandrem/FlyCasual#1326]
I've been trying to line up games via discord and play, but typically one of the following happens:

- game crashes one on or both sides while trying to join room

- game loads but crashes at some point in the game (often early on, before end of turn 1) with no red error text, just a freeze on both ends.   Game stops responding.  

This isn't unique to me - seems like everyone I've chatted with is having similar challenged trying to play in internet mode.  I'm using a PC.  Last two matches that crashed I was using PC, opponent was using mac.

Thanks!

**Comment by McLaine** [comment]
It happens for me directly after my opponent attempts to place his 2nd or 3rd ship on the mat.

So far, it's been Old Teroch or Bobba Fet, but suspect it's more their order of placement rather than specific ship.

Getting some null object reference errors in the console when it happens.

It hasn't happened yet for me when playing Offline modes.

I have tested the online squad of my opponent as an AI opponent, no errors.

Sometimes the error fails gracefully, posting once to the console, and the command 'close' allowing the game to continue.

Other times, it seems like a loop is posting to the console, causing the game to not progress and the camera movement stutters.

**Comment by Sandrem** [comment]
Online mode is sent to be reworked.
Current bugs of this mode are closed.
