### ISSUE TITLE
AI moves right in front of asteroid

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1520]
Should take obstacles into account when planning 

![screenshot_20190208-081339](https://user-images.githubusercontent.com/11047987/52469558-0ae97a80-2b8c-11e9-91b7-04c230b95442.png)

**Comment by Sandrem** [comment]
AI tries to have a chance to shoot this turn with higher priority than tries to avoid asteroids next turn.
I will see what I can do with priorities...

**Comment by rune-b** [comment]
It does this even when there is no chance of shooting

![image](https://user-images.githubusercontent.com/11047987/52506204-179eba80-2bee-11e9-95d1-efdaeb279ec6.png)

**Comment by bitsai** [comment]
IMHO not a bug, per se, since humans sometimes also do things like prioritize shots over avoiding obstacles, or mis-judge distances and put ships in front of obstacles even when there's no shot :)  Moving this to the Requested Features Wiki (https://github.com/Sandrem/FlyCasual/wiki/Requested-Features).

**Comment by Sandrem** [comment]
AI can move right in front of asteroid to get a shot, but if it does this when no target is available - this is a bug. Seems that something is wrong in prediction, "Am I in front of asteroid?" check.

**Comment by Sandrem** [comment]
Fixed
