### ISSUE TITLE
Collision Detector Issue

### ISSUE THREAD

**Issue by sthej** [Sandrem/FlyCasual#1565]
If I perform a move that overlaps two obstacles, CD will trigger twice. At least it gives me the option of blowing both charges (which I did--and it went from 2 to 0 charges). I haven't tested using one then selecting the option to not use CD.

**Comment by bitsai** [comment]
As best as I can tell, this is the correct behavior.  From the wording, when you use a charge it allows you to ignore the effects of one specific obstacle.  And since CD does not have a stated limit on how many times it can trigger in a round, if you flew over two obstacles, you should get the option of triggering CD twice.
