### ISSUE TITLE
Ruthless & Elusive

### ISSUE THREAD

**Issue by rashktah** [Sandrem/FlyCasual#1570]
A) AI uses 'Ruthless' even when there are no friendy ships in range as described on the card.

B) When Talon-rolling, B-Wings can't decide if the end position is front/center/back as they are always put at the center marking.

C) 'Elusive' reroll is available after defense dice have already been rerolled (eg by Braylens' ability).

**Comment by rune-b** [comment]
I have also had some strange behavior with Elusive. AI using both elusive and another ability on the same die

**Comment by bitsai** [comment]
A) fixed by #1574

B) currently a planned feature: https://github.com/Sandrem/FlyCasual/wiki/Planned-Features

C) re-tested this in latest release (0.9.2) using Braylen w/ Elusive + Stealth Device.  Braylen's ability & Elusive are both available on defence (which is correct), and any dice re-rolled by Braylen's ability are locked from being re-rolled again by Elusive (also correct).
