### ISSUE TITLE
Proposed random squads for 0.8.0

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1647]
It would be nice to have more random squads for the AI. Here are some suggestions:

### Rebel:
4 x Gold Squadron Veteran (33)
   Ion Cannon Turret (4)
   R4 Astromech (2)
   Shield Upgrade (4)
   Veteran Turret Gunner (6)

### Empire:
Omicron Group Pilot (43)
    Admiral Sloane (10)
    Perceptive Copilot (8)

6 x Academy Pilot (23)

### Scum:
5 x Cartel Marauder (40)

### Resistance:
4 x Blue Squadron Rookie (46)
   Integrated S-Foils (0)
   Advanced Optics (4)

### First Order:
3 x Omega Squadron Expert (36)
   Fanatical (2)
   Special Forces Gunner (10)

"Backdraft" (41)
   Fanatical (2)
   Special Forces Gunner (10)

**Comment by rune-b** [comment]
Anyone else have any good AI lists?

**Comment by bitsai** [comment]
@rune-b you may have seen this already, but just a couple days ago someone started a Reddit thread about good FlyCasual AI lists and I think there are some good ones there:

https://www.reddit.com/r/XWingTMG/comments/axlg6i/fly_casual_question/

**Comment by rune-b** [comment]
@bitsai  I am aware, it's where I got several of the squads from.

**Comment by bitsai** [comment]
Added 6 more random AI squads in https://github.com/Sandrem/FlyCasual/pull/1696.

I added all of @rune-b's squads except for the 4 Yions; as mentioned in the Reddit thread, the AI currently points the turrets backwards, making Veteran Turret Gunner (and therefore the whole list) kinda toothless.

Also added some squads from the Reddit thread linked above, skipping ones that seemed redundant, under-specified (like the 5 K-wings list), or possibly buggy (the Chewie + RZ-2's list, because of https://github.com/Sandrem/FlyCasual/issues/1670).
