### ISSUE TITLE
Unable to select any of my ships after attack by Special Forces Gunner

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1718]
https://i.imgur.com/eZhN6Ci.jpg

UPD: fixed by hitting Skip
UPD: can be linked to Backdraft attacking, not to Grievous

**Comment by DejaFu** [comment]
I ran into the same issue, only it was after 4 Omega Squadron pilots attacked.  Ahsoka Tano was the only one left to attack and I couldn't select her.  Due to your bug report, I tried selecting "Skip" and that allowed me to select her and attack.
![image](https://user-images.githubusercontent.com/48073298/55560654-ebfbf600-56ad-11e9-976c-c0b2b07f2942.png)

**Comment by rune-b** [comment]
It seems to be tied to special forces gunner. I played a tie swarm against the SF squad and every time after the SF's had attacked I couldn't select any of my ships. Clicking on Skip solved the problem. Seems there is a subphase or something that's not properly ended

![Screenshot_20190412-172927](https://user-images.githubusercontent.com/11047987/56049953-e906a280-5d4a-11e9-8c4c-c5fb865f66e6.png)

**Comment by bitsai** [comment]
I've had some test battles against the Omega Squad Experts list and the Backdraft list in the latest development branch, and am no longer seeing this issue.  Closing for now, but please feel free to open if you see this again in release 0.9.1.1 or later!
