### ISSUE TITLE
M12 kimogila pilot abilities do not ever trigger (Torani & Dalan)

### ISSUE THREAD

**Issue by username2065** [Sandrem/FlyCasual#1721]

**Comment by rune-b** [comment]
Torani's ability triggers for me. Has this happened more than once for you? Do you remember which ships/upgrades you used?

![image](https://user-images.githubusercontent.com/11047987/55436563-f67a9a80-559c-11e9-94bd-7551ea35ce2a.png)


Dalan is bugged, he is given Torani's ability instead of his own. I will fix this.

**Comment by Sandrem** [comment]
Dalan is fixed
