### ISSUE TITLE
AI Kraken locks up when choosing 3 targets to keep calculate tokens

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1795]

**Comment by bitsai** [comment]
@Sandrem in Slack it was theorized that this is due to `subphase.RequiredPlayer` not being set, but it looks like that is already set here: https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Content/SecondEdition/Upgrades/TacticalRelay/Kraken.cs#L57

Could it be that AI needs to support `MultiSelectionSubphase` somehow?

**Comment by Sandrem** [comment]
AI is added
