### ISSUE TITLE
R5-P8 causing damage on non-crit results.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1841]
This is 0.8.1, not sure how else to expand on this issue.

**Comment by bitsai** [comment]
@Sandrem after looking at the code, I think the issue is that the current implementation causes damage if *any* of the final dice result is a crit, when the card says damage should be only be done if the dice result rerolled by R5-P8 is a crit.

is there a way to get the most recently re-rolled dice result?

**Comment by Nitroxylin** [comment]
The issue is still present.

**Comment by Sandrem** [comment]
Fixed
