### ISSUE TITLE
0.8.2: What does the Wounded Pilot card actually do?

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1874]
![Clipboard05](https://user-images.githubusercontent.com/30575527/57414041-33225d00-71ff-11e9-8a5d-3e7e987b47da.jpg)
![Clipboard06](https://user-images.githubusercontent.com/30575527/57414049-3c132e80-71ff-11e9-86f0-e69e8565025b.jpg)

The cards differ in whether the roll happens after an action or after an attack; moreso, it was for some reason rolling a die when this pilot was tractoring himself.

**Comment by bitsai** [comment]
@Nitroxylin based on https://xwing-miniatures-second-edition.fandom.com/wiki/Damage_Cards, I think the version that says "After you perform an **action**..." is correct, and looking at the code, I think that's the version that is implemented.

My guess is that a die was rolled because the pilot tractored himself by using the ship's Pinpoint Tractor Array ability to perform a rotate action, which then triggered Wounded Pilot.
