### ISSUE TITLE
Electro proton bombs crash the game

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#2001]
![image](https://user-images.githubusercontent.com/6347443/60395252-7af79d80-9b39-11e9-8d6f-666c8be10270.png)

Source: Discord, Samuel Melhado
#5464

**Comment by bitsai** [comment]
If you zoom in on the screenshot, the EPB was carried by Finch Dallow.  From the stack trace, I suspect this error was caused by the lack of initialization on bombs dropped using Finch's ability, which was just fixed as part of https://github.com/Sandrem/FlyCasual/pull/2026.

Tested this setup using the latest development branch, and I was able to drop EPB both with and without Finch's ability without errors, so I think this has been fixed.
