### ISSUE TITLE
[0.9.1.1] Attempting to fire Cat's primary guns results in an error

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2019]
![pt1](https://user-images.githubusercontent.com/30575527/60740856-e4c7db00-9f6f-11e9-88ae-41448206253f.jpg)
![pt2](https://user-images.githubusercontent.com/30575527/60740862-e85b6200-9f6f-11e9-9997-b9a709ceb62d.jpg)

**Comment by bitsai** [comment]
Hmmm, based on the stack trace, the error happened when the game code is cycling through each bomb in the game and checking the ships in range of each bomb.

I tried to reproduce the bug by doing the following:

- drop a proton bomb behind Cat and let it detonate, then firing Cat's primary
- drop a proximity mine behind Cat and let it stay on the board, then firing Cat's primary
- use Trajectory Simulator to put a proton bomb with Delayed Fuse on top of the enemy (to make sure there's a friendly device in range), then firing Cat's primary

... but was not able to reproduce the issue.

@Nitroxylin do you mind trying to reproduce the issue again (FYI, I usually find it easier to reproduce bugs using Hotseat mode instead of playing the AI)?  And if you are able to, can you provide the full friendly + enemy ship lists as well as the exact steps used to reproduce?

**Comment by Nitroxylin** [comment]
Reproduced.
 - ships coming up close
 - Finch firing at the VT-49, then deploying a bomb as per Paige's ability
 - Cat attempting to fire at the VT-49 after that

![pt5](https://user-images.githubusercontent.com/30575527/60772440-2dfa6500-a0ff-11e9-99d6-976fabaaa5b9.jpg)

**Comment by bitsai** [comment]
@Nitroxylin thanks for the detailed info!  I was able to reproduce it now as well.  I suspect it has something to do with the way Finch's ability deploys bombs.  Will try to get this straightened out ASAP.  Thanks again!
