### ISSUE TITLE
Boost action saves old direction

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#2099]
> One bug I'm getting though is when I boost with a ship, it will frequently just boost in a random direction instead of allowing me to choose. Bit problematic practising with arc dodgers at the moment! I'm getting this issue in version 0.9.2 on both Windows and Android. I'm not sure, but it might be getting stuck on the same direction you first choose to boost in.

Source: https://www.reddit.com/r/XWingTMG/comments/ccg3l5/fly_casual_version_092/eu1yim7/

Seems that boost action doesn't clear chosen direction. (Maybe after failed boost or after use of another boost-related ability)

**Comment by bitsai** [comment]
@Sandrem your intuition was right on the money; I was able to reproduce this by failing a boost:

- first turn, use regular action to attempt and fail to Boost into an obstacle
- second turn, when Boost is selected again for regular action, the previous Boost direction is executed immediately

Looks like I cleared the chosen Boost direction in the wrong place in my old PR (#1902), because `FinishBoost` doesn't get called on a failed Boost.  Will look for a better place to clear it.
