### ISSUE TITLE
Bomb drop issues

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2141]
In the systems phase, if there is only 1 ship with 1 bomb it will drop automatically when the ship is clicked. This confused me as I thought I was in the activation phase and dropped a bomb unintentionally when I clicked the ship. There should be some decision/confirmation UI before dropping the bomb

**Comment by Sandrem** [comment]
Seems that I broke this in one of my lastes changes. I will take a look.

**Comment by bitsai** [comment]
A related (and IMHO critical) behavior: if you decide to SKIP a ship with bombs during turn 1 System Phase, then click that ship during turn 2 System Phase, you now have 2 bomb drop triggers:

<img width="1280" alt="Screen Shot 2019-08-05 at 6 33 16 PM" src="https://user-images.githubusercontent.com/260863/62505067-fe975080-b7af-11e9-8cf9-89acedc77649.png">

And because neither are skippable, you are now forced to drop multiple devices that turn:

<img width="1280" alt="Screen Shot 2019-08-05 at 6 33 30 PM" src="https://user-images.githubusercontent.com/260863/62505171-4b7b2700-b7b0-11e9-88c5-1df474aac0da.png">

So currently in the dev branch, ships with bombs either have to drop a device every turn, or are forced to drop multiple devices the first time they do not skip System Phase activation.

**Comment by bitsai** [comment]
To expand on rune-b's original report, currently in the development branch, if a ship with multiple devices is clicked during the System Phase, it will drop/launch the first device instead of asking the player which device to drop/launch.

**Comment by bitsai** [comment]
After the work that was done in 981c4f4e9055bfca017f5764b847b143ecbcfa9a, I re-tested the latest development branches and can confirm that all problems reported in this issue (as well as abilities that used `OnSystemsAbilityActivationGenerateListeners`, such as Grand Moff Tarkin crew) have been fixed.  Thanks for looking into this, @Sandrem !
