### ISSUE TITLE
Ketsu Tractor beam

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2173]
Latest edition of the game 0.9.3 on Windows 10, if an enemy ship is tractored by either Ketsu pilot ability or by the Shadow Caster title and they end up on an asteroid, they can still shoot. I also noticed that when the animation of their shooting happens it seems to originate from where they ended their manouevre, rather than where they were tractored to.

**Comment by TooheysN00b** [comment]
+1 for this issue.
Reproduces every time.
Also if Ketsu is on a rock after movement and uses her ability, system rolls for rock damage on Ketsu again.
I have two screenshots attached for enemy ship on rock issue.
![Tractor rock 1](https://user-images.githubusercontent.com/33504209/63206715-52793200-c0ec-11e9-88b5-7b22d95446b7.jpg)
![Tractor rock 2](https://user-images.githubusercontent.com/33504209/63206716-5311c880-c0ec-11e9-8bf7-2a24e7d5fdbc.jpg)

**Comment by darkflop** [comment]
Issue still happening in v0.94
Not necessarily linked to Ketsu's ability. Any tractoring effect throwing a ship on an asteroid will not prevent that ship from shooting.

**Comment by krumok** [comment]
Yes confirm, still in 0.9.4.
After a barrel roll caused by Ketsu ability, if the tractors ship is on asteroid it can shoot.
It happens every time.

![Screenshot_2019-08-27-22-51-18-276_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/63831050-0345c380-c96e-11e9-8dcf-dc525d5b1a75.jpg)
Here Wedge, over an asteroid, is shooting to Ketsu


![Screenshot_2019-08-27-22-41-16-474_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/63831207-69324b00-c96e-11e9-855c-9c909ed08090.jpg)
Here ywing the same
