### ISSUE TITLE
Request: rephrase adaptive ailerons for Duchess positively, to avoid a double negative when making the decision

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2195]
Right now the popup reads "Do you want to skip the use of Adaptive Ailerons?" if you answer No, you are basically choosing a double negative (not skipping). It reads much easier to frame it positively:

"Do you want to use your Adaptive Ailerons?" Yes or No.

**Comment by bitsai** [comment]
I personally prefer the current wording because it maps closer to the wording on Duchess' card (https://xwing-miniatures-second-edition.fandom.com/wiki/%22Duchess%22), but I also see your point about the double-negative being potentially confusing.

@Sandrem what do you think?  If you're ok with the proposed wording change, I can implement it (and the small associated code change) in my open PR for Duchess (https://github.com/Sandrem/FlyCasual/pull/2198).

**Comment by bitsai** [comment]
After thinking about it some more, I like the wording change suggested by @pinosante and have implemented it in https://github.com/Sandrem/FlyCasual/pull/2198.
