### ISSUE TITLE
Anakin Skywalker can't use Afterburners after the 5k

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2202]
Anakin did a pre-boost forward with Supernatural Reflexes, then a 5k, and then I chose "Afterburners" and got the red warning message that Anakin can not do any free actions. He should be able to.

**Comment by bitsai** [comment]
The behavior as implemented is correct; both Supernatural Reflexes and Afterburners give you additional windows to perform actions, but each specific action (ex. Boost) can only be performed once per turn, unless the card makes an explicit exception (ex. Anakin in the Naboo Starfighter).

In this case, since you already performed the Boost action with Supernatural Reflexes, when Afterburners (which only allows you to perform the Boost action) was triggered, there was no legal action to perform, hence the warning message.

**Comment by pinosante** [comment]
My bad, thanks.
