### ISSUE TITLE
AI: Han Solo (Modified YT-1300) uses his ability near asteroids on any chance he gets.

### ISSUE THREAD

**Issue by ggrabarz** [Sandrem/FlyCasual#2249]
Even if that means rerolling his sole Evade to Blank or Focus.  His card says **may**, not **must**.
While tokenless, also shouldn't reroll (unless facing death without trying it): 
- two Evades with a Focus/Blank (range 3 through a rock) 
- one Evade with a Focus/Blank (range 3 or through a rock)

since evade symbols have only 3/8 chance of appearing. 
The math changes depending on available Calculates/Focus/Force tokens.

![HanSoloRebelPilotCard 2](https://user-images.githubusercontent.com/22742383/64054559-cf45ea80-cb87-11e9-8ae4-d1d34ff5fa34.png)

**Comment by bitsai** [comment]
As mentioned in #2233, there are a lot (> 600) cards in the game, so detailed AI for any specific card has low priority/pay-off.  Especially for an ability like Rebel Hans, which has potentially many factors to take into consideration, as you pointed out :)  I've tweaked the AI so instead of always using Hans' ability, it will only use it if the # of Blank/Focus results > # of Evade/Hit/Crit results (depending on whether the AI is attacking or defending).  It's a simple heuristic, but one that is hopefully a small step forward.  Something more sophisticated will have to wait for later.
