### ISSUE TITLE
Anakin slooped, took stress off for range 1, then the shot was range 2

### ISSUE THREAD

**Issue by mishari27** [Sandrem/FlyCasual#2251]
This is strange,

Anakin slooped, and the game gave me the chance to spend a force to remove stress, so I assumed the shot was R1. but when I shoot, it's 3 dice only. weird.
![ani sloop](https://user-images.githubusercontent.com/54389008/64076416-56e94180-cccd-11e9-9795-87e36803150e.jpg)

**Comment by bitsai** [comment]
There's a small bug in Anakin's ability that triggers it if there's an enemy ship anywhere within range 1 if any part of that ship is in arc, even if the part that is in arc is actually outside range 1.  I believe that's what happened here: the closest corner of the TIE is in range 1, but due to the relative angles, the part that is actually in arc is just outside range 1 of Anakin.

Bug has been fixed in development branch, and will be resolved in the next release.
