### ISSUE TITLE
Arvel range 0 attack not being allowed

### ISSUE THREAD

**Issue by SleepyJedi** [Sandrem/FlyCasual#2275]
Can still perform incomplete boost into enemy ship, but can't attack at range 0

**Comment by bitsai** [comment]
Wasn't able to reproduce; here's Arvel just after Focusing and then using Vectored Thrusters to boost into an enemy TIE (see the red message about having collided into another ship):

<img width="1280" alt="Screen Shot 2019-09-06 at 9 13 37 PM" src="https://user-images.githubusercontent.com/260863/64469699-8b089c00-d0eb-11e9-8a42-d35bb0a697e4.png">

Arvel was able to shoot that TIE at range 0 without issues:

<img width="1280" alt="Screen Shot 2019-09-06 at 9 13 47 PM" src="https://user-images.githubusercontent.com/260863/64469706-9cea3f00-d0eb-11e9-94b5-23e8ee9110d5.png">

Can you try to reproduce the problem?  If so, do you mind sharing the steps taken and also screenshots?

**Comment by SleepyJedi** [comment]
I was actually unable to reproduce when using just Arvel with Intimidation and an Academy Pilot as well, so I tried replicating it with the list I'd been flying. I wasn't able to reproduce the "Not a valid target" message for Arvel with a range 0 target, but I did end up getting this...
![Untitled](https://user-images.githubusercontent.com/26986510/64470474-58b16b80-d0f8-11e9-9884-0567dd6a9d07.jpg)

**Comment by SleepyJedi** [comment]
I did notice that the HWK continuously had what looked like the firing animation coming out of it's front, so I don't know if that is causing other issues. You can see the red streak in the screenshot

**Comment by Sandrem** [comment]
@SleepyJedi What speed of movement do you use in options?

**Comment by SleepyJedi** [comment]
Presumably default. This is what is shown in the app
![Untitled](https://user-images.githubusercontent.com/26986510/64478880-0c037a00-d164-11e9-8aeb-bb144236952f.png)

**Comment by bitsai** [comment]
Tracking this under bumping-related problems meta-issue (#2279).

**Comment by bitsai** [comment]
Just reproduced this: turns out that while Arvel can shoot a target if he Boosted into it, if he flew into it with a normal maneuver he is not able to shoot it like he's supposed to.

Steps to reproduce using a Hotseat game:
- set up Arvel and a TIE fighter (or anything else with a 5-straight) directly across from each other, as far forward as possible
- first turn, do a 5-straight with both
- second turn, do a 2-straight with both
- during Engagement, Arvel is not able to shoot the ship he's bumping

<img width="1280" alt="Screen Shot 2019-10-01 at 8 34 14 AM" src="https://user-images.githubusercontent.com/260863/65977384-b0f13a00-e426-11e9-9675-f57645f16f5d.png">

**Comment by bitsai** [comment]
Note: attack is failing because when `GetAvailbleAttackTypes` is called from https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Combat/Combat.cs#L139, there are no weapons for which `shipWeapon.IsShotAvailable(anotherShip)` = true.

**Comment by Sandrem** [comment]
Fixed
