### ISSUE TITLE
Wedge does not trigger Viktor Hel's ability

### ISSUE THREAD

**Issue by kthorsnaes** [Sandrem/FlyCasual#2324]
Wedge (Rebel X-wing) does not trigger the ability of Viktor Hel (Scum Kihraxz Fighter) when he attacks him.

**Comment by rune-b** [comment]
I'm not able to reproduce this. I tried shooting Viktor Hel with Wedge at close range, causing him to roll only on defense die, and his ability was triggered. Also tried at range 3 where the ability did not trigger, since Wedge reduced defense dice to 2

![Screenshot_20191005-201834](https://user-images.githubusercontent.com/11047987/66259130-b693aa80-e7ad-11e9-90fb-980e0fc6c624.png)
![Screenshot_20191005-201841](https://user-images.githubusercontent.com/11047987/66259132-bbf0f500-e7ad-11e9-9147-2ad1e1c5a9a7.png)


Also did the same test with Outmaneuver, with the same result 

![Screenshot_20191005-201855](https://user-images.githubusercontent.com/11047987/66259142-d1feb580-e7ad-11e9-85a2-aa6369f0f0f4.png)
![Screenshot_20191005-201902](https://user-images.githubusercontent.com/11047987/66259144-d925c380-e7ad-11e9-94f7-8c63030fa72d.png)

**Comment by kthorsnaes** [comment]
I can't reproduce this myself either and I foolishly did not note down the other ships in the list.
