### ISSUE TITLE
Grand Moff Tarkin (crew) does not give other friendly ships a target lock

### ISSUE THREAD

**Issue by thomedwards** [Sandrem/FlyCasual#2434]
Grand Moff Tarkin should allow each ship to acquire a lock on a ship that is locked by the ship carrying Tarkin. 

When you select the ship with Tarkin in the System phase, you can only choose to lock the same ship (it is already locked by the carrying ship) with the carrying ship. There is no option to allow other friendly ships to lock that ship.

I have seen it work as expected once. But, three other attempts it behaves as described above.

**Comment by rune-b** [comment]
Were those ships within range 3 of the target ships? Even if there is no range restriction on Tarkin's ability, they still have to be in range to be allowed to do a lock

Page 12 of the rules reference states "If a ship is instructed to acquire a lock, the object it locks must be at range 0–3 unless otherwise specified."

**Comment by rune-b** [comment]
Just tried this, and did not get any option to lock even if well within range

**Comment by rune-b** [comment]
No, I can't reproduce this. Not sure what I did last time, but the screen shot is not from the systems phase, so I think I just misunderstood the timing. It works fine now, Both Tarkin and the interceptor within range gets the option to lock

![image](https://user-images.githubusercontent.com/11047987/75817607-b668fc80-5d97-11ea-96f0-e76148c721e6.png)

**Comment by Sandrem** [comment]
Still cannot reproduce
