### ISSUE TITLE
Qi'ra lock rocks

### ISSUE THREAD

**Issue by XWINTERS86X** [Sandrem/FlyCasual#2443]
Qi'ra still cant target lock asteroids to use her ability.

**Comment by Spyke114** [comment]
I just tested it and found it working almost completely properly. If you're playing on mobile then you'll have to change controls from "Touch" to "Mouse" to select the obstacle and then change back to touch after.
This works for Seismic Charges too, btw.

The only thing about Qi'ra that wasn't working for me was not being able to boost onto my locked rock, so that could use a fix at least.

**Comment by Sandrem** [comment]
Fixed
