### ISSUE TITLE
AI pathing bug

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2471]
I'm not entirely sure where the source of the bug may be or what caused it. As I understand the aggressor AI (From the squadron benchmark AI implementation, which has looked similar to this) there are 2 parts to this bug. 

Part 1: Every ship has a "Default maneuver" or the maneuver it does when it doesn't know what to do. This is typically the slowest straight maneuver it can perform, and still stay on the board. (In squadron benchmark, this could sometimes create a scenario where a ship does red full stops repeatedly, and sometimes even stop attacking). Theoretically we should never see this in a standard match, but once you know it exists, its behavior can become easy to spot, as a ship orbits the edge of the board doing short straight maneuvers.

Part 2: We should never see the "default maneuver," but apparently something can be done to trigger it, and keep it on at least until something dies, at which point the Aggressor AI starts to make choices again. (Though it looks like it might be picking random of available maneuvers that don't fly it off the board) My guess right now has to do with seismic charges deleting an obstacle from an array, meaning the AI pathfinding keeps looking through null for a distance to target. If I knew how to fire up the console I'd happily give you whatever logging statements come up during that window

**Comment by rune-b** [comment]
I have also experienced this. Sometimes, for instance, an AI X-Wing will just keep doing 1 straights away from the action until it reaches the edge. Then it will turn around and rejoin combat

**Comment by Sandrem** [comment]
I fixed following problem:

Old AI:
AI tries to finish manuver as much close to the nearest enemy ship. If this maneuvers allows to shot at enemy ship - such maneuvers is prioritized.
But sometimes there are situations where the nearest enemy ship is behid AI ship. And if AI uses K-Turn - it still don't see it in arc due to distance.
So AI tries to be as much close as possible, so perfroms "min straigt" maneuver again and again until reaches end of the map and needs to turn.

New AI:
AI also checks "angle to enemy". Now it tries to have enemies in front of itself, even if range is too big for attack. So It now perfroms K-Turns in mentioned situations.
