### ISSUE TITLE
Issues with the fireball

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2498]
Hi, here are some bugs reporting about Resistance's new ship:
-the 3 straight is blue instead of white
-3 pilots are lacking (there's only Kazuda)
-the title is not available
-R1-J5 droid card is not available
-Coaxium Hyperfuel doesnt' work when you bump into other ships (you should be able to SLAM)

Good Day, and thank you for FlyCasual, it's great!

**Comment by rune-b** [comment]
Thanks. 
I will fix the 3 straight
It is not necessary to report missing cards, we know. It just takes time to implement them all

About Coaxium

Coaxium Hyperfuel says:
After you partially execute a maneuver, you may expose 1 of your damage cards or suffer 1 crit damage to perform a SLAM action.

From the SLAM action section in the rule book:
A ship can perform a SLAM action only as the ship’s one action during the Perform Action step. **Therefore a ship cannot perform a SLAM action if it is granted an action from another effect.**

The reason it doesn't work is because FlyCasual implements the SLAM rule, preventing the card from granting a SLAM action. But I guess the SLAM rule doesn't apply if the effect that grants the action specifically grants a SLAM action
