### ISSUE TITLE
Reinforce doesn't work when triggered by Lando Calrissian ability

### ISSUE THREAD

**Issue by Grande-Rojo** [Sandrem/FlyCasual#2653]
Reproduced issue when deflector shield modification is used by Rebel X-wing (2nd ed).  If X-wing is equipped with deflector shields mod and reinforces via their own action, reinforce works as normal during combat.  If X-wing executes different action as part of their turn and reinforce is triggered by Lando Calrissian's ability from the falcon (on blue maneuver, friendly can execute additional action), then during combat the reinforce does not work.  Have not tried to see if same effect occurs during coordinate or if the same is true with deflector shields on other ships.

**Comment by Sandrem** [comment]
I just checked - ability of Lando Calrissian granted reinforce action from Angled Deflectors to a X-Wing. Then X-Wing was attacked by 3 ships, 2 of them had "2 hits" after defense dice, and in each case reinforce worked correctly - X-Wing received 1 hit and then 1 hit too.

Maybe you had a situation where only 1 hit is dealt and SE reinforce doesn't work due to SE rules change?

Please, if you can reproduce this bug - send me replay from "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual\Second Edition\Replays"
