### ISSUE TITLE
Cluster missle not operating correctly

### ISSUE THREAD

**Issue by utahmanalex** [Sandrem/FlyCasual#2662]
When using cluster missles, the card states you can do this attack again against another defender that is within 0-1 distance of the first defender. This is only working when I the attacker am within 0-1 of the defender. This should be the other way around.

**Comment by Sandrem** [comment]
I just checked - and successfully attacked with second attack a ship that was at range 2 from attacker and at range 1 from original defender.

Please, next time provide screenshot. Maybe, second target was at range 3 from attacker, so Cluster Missiles couldn't be used because they have range only 1-2.
