### ISSUE TITLE
Dengar Gunner causing manager to open

### ISSUE THREAD

**Issue by Sergovan1** [Sandrem/FlyCasual#2665]
I think the issue is that the choice to resolve to spend a green token for the enemy ship is given to the player.
![Screen Shot 2020-05-22 at 6 42 01 AM](https://user-images.githubusercontent.com/64314306/82660261-0bc6e400-9bf8-11ea-9c36-6a682f6af17e.png)

**Comment by grandpajive** [comment]
I've seen that with Torani Kulda's ability as well. I saw in your dengar fix that the ai chooses option one so I've have the AI to lose the green token if they have one instead of taking damage (I wouldn't heh). Then I type close in the console drop down. And then the ai swarms and kills Torani heh.

**Comment by Sandrem** [comment]
Both issues are fixed in v1.2
