### ISSUE TITLE
Homing Missiles Bug

### ISSUE THREAD

**Issue by jasperordash** [Sandrem/FlyCasual#2668]
Not sure where the problem is but I hope you find the attached screenshot usefull...

Thanks
<img width="1678" alt="Captura de pantalla 2020-05-24 a las 20 22 46" src="https://user-images.githubusercontent.com/59624897/82761724-ea831500-9dfc-11ea-8f84-a2d02204051a.png">

**Comment by Ember369** [comment]
Hi there, I'm not too sure if this is quite the same error as the one jasperordash described, but I thought I might comment here instead of creating a new duplicate issue. I've uploaded a screenshot and my LastReplay.replay file just in case. Hope it helps!

![Homing Missile Error](https://user-images.githubusercontent.com/59035469/85919987-438a1100-b8b3-11ea-967a-a8766d657afd.png)

The homing missiles seemed to work earlier when attacking from the main firing arc from the TIE/SF Fighter, but not when firing them from the gunner's arc. Could that potentially be the cause? Anyway, happy bug fixing!

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/4840298/LastReplay.replay.zip)

**Comment by Sandrem** [comment]
Finally fixed
