### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by idjmv** [Sandrem/FlyCasual#279]
When I try to run the program, it will say "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." 

Please fix, I am really looking forward to this

**Comment by Sandrem** [comment]
Hello. Seems that this is not game-related problem.
Try these advices https://support.microsoft.com/en-us/help/2669244/-windows-cannot-access-the-specified-device--path--or-file-error-when
Check where files where extracted, try re-download zip-archive, finally try to turn off antivirus.

**Comment by idjmv** [comment]
I tried everything, but it still has the issue

**Comment by Sandrem** [comment]
What antivirus do you use?

**Comment by idjmv** [comment]
Sorry for the late response. Avast (Free Version)

**Comment by Sandrem** [comment]
I got feedback that Avast and AVG don't allow to start my game (because this exe-file is new and unknown to their databases).
I wrote to Avast letter about false virus report and seems that they fixed this problem.
Please, try to update antivirus database and try to downloand/launch game again - is it OK now?

**Comment by idjmv** [comment]
Ok it works now, thank you
