### ISSUE TITLE
Decloaking+Collision Detector/Object Interaction Issue

### ISSUE THREAD

**Issue by M1ntyPunch** [Sandrem/FlyCasual#2862]
Using "Echo" in the TIE Phantom with Collision Detector:

I decloak, barrel rolling onto an asteroid, where the front half of my ship is off of it. It asks if I want to use CD, I decline. It correctly has me roll for damage and let's me perform my bonus evade action. However, once I maneuver, it skips my perform action step, despite not maneuvering over an obstacle again. 

Other possibly helpful tidbit is that it didn't have me roll for damage again, so I'm pretty sure it just mistakenly skips the normal action from decloaking onto a rock.

Love your work, keep it up!

**Comment by tmo7452** [comment]
I think this is the same issue I came to report.
**Issue:** Decloaking off an obstacle incorrectly triggers Collision Detector.

**Steps to reproduce:**
1) Equip a TIE/ph with Collision Detector
2) Fly it over an obstacle such that one side is completely unobstructed. (Right side in this case)
![image](https://user-images.githubusercontent.com/9245957/105071065-1caf4a00-5a52-11eb-85cb-0377b111e35e.png)
3) Cloak
4) During system phase, choose to decloak to the unobstructed side.

**Expected result:** Decloak no prompt to use Collision Detector.
**Actual result:** I get prompted to use Collision Detector, and suffer penalties for overlap if I decline.
![image](https://user-images.githubusercontent.com/9245957/105071431-96473800-5a52-11eb-9658-b2db63bc5bab.png)

**Notes:** This only occurs if Collision Detector is attached. Without it, decloaking off obstacles works fine. It appears CD is making it check the start location for obstruction, instead of just the template and end location.
**Replay:** [LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/5837585/LastReplay.zip)

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3136
