### ISSUE TITLE
"Ship has already already executed their maneuver"

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2865]
No, Boba has not executed his maneuver yet. He's also blinking and it should be his turn. Selecting him only gives the lower error message.

![image](https://user-images.githubusercontent.com/28895989/89797764-9e0dc280-db2b-11ea-94e3-1703bd1db5cf.png)

**Comment by justinkid01** [comment]
Do you remember if your Rogue Squadron Escort failed an action just before this occurred? I was having the same issue today (receiving the message "This ship has already executed their maneuver"), and we noticed it only occurred after the ship before it failed an action. See my report for more info: https://github.com/Sandrem/FlyCasual/issues/2870

**Comment by VexingVision** [comment]
No, the Rogue Squadron was played by the AI, which has yet to fail a single action in any game I played against it.

But you are right - there should be a Target Lock or a Focus on the enemy ship, I don't remember what action it did instead - maybe that's the cause!

**Comment by grandpajive** [comment]
I had that occur when I mouse click failed while at moved, right clicked it clicked on my ship prior to movement. Don't remember the full details but you're not alone. Will try to reproduce the issue.

**Comment by justinkid01** [comment]
VexingVision, 
That is interesting! In my case, the issue only occurred during online play against another human. I've never had the game freeze after failing an action while playing against the AI, although I haven't tested what happens when an AI fails an action because as you said, it's extremely unlikely that the AI would ever fail an action (perhaps impossible?). In your case, however, the lack of focus or target lock may indicate a failed action by the AI (unless of course the AI had barrel rolled or boosted and chosen not to take the stress for an additional action).

**Comment by Sandrem** [comment]
Some fixes are done.
