### ISSUE TITLE
Nantex, red maneuvers and tractor beam.

### ISSUE THREAD

**Issue by elTitoMalo** [Sandrem/FlyCasual#2869]
Nantex should not be able to receive a tractor beam after performing a red maneuver.

**Comment by rune-b** [comment]
Hmm. Are you sure that is the correct interpretation of the rules? I believe you are correct, but I'm not 100% sure. The ability rules say you can only pay for an ability if you are able to resolve it, but is gaining a token considered "paying a cost"?

**Comment by ChrisStricker** [comment]
He is correct.  The problem is that the ship cannot take the rotate turret action while stressed.  A ship can only pay a cost if the effect can be resolved.  Since it cannot take the rotate turret action, it cannot resolve the ability, Since it cannot resolve the ability, it cannot pay the cost and does not gain a token.

This should also be true if the ship is stressed and executes a white maneuver.

**Comment by rune-b** [comment]
Yes, you are correct. I will fix it
