### ISSUE TITLE
Autoblaster locking Crits in Front Arc

### ISSUE THREAD

**Issue by SlayerOfTheStars** [Sandrem/FlyCasual#2889]
Autoblaster incorrectly locks crits when in the front arc of ships that do not have a printed front firing arc.
![Autoblaster](https://user-images.githubusercontent.com/40924222/91504500-29a08680-e882-11ea-8602-ecb8cb96c0f9.png)

**Comment by rune-b** [comment]
This is not a bug I think. All ships have a front arc whether or not it is colored on the base

**Comment by Sandrem** [comment]
Second Edition uses "sectors" instead of FE "firing arcs".
All ships have front / rear / side sectors. (For example, YT-1300) can shoot missiles using front sector, even if it's turret firing arcs are pointed left and right.

As I understand, problem is that ability is activated, while defender has attacked in front sector.
Maybe code checks "forward facing firing arc (FE rules)" instead of sector.

**Comment by Sandrem** [comment]
Fixed
