### ISSUE TITLE
Garven Dreis Issue with Focus

### ISSUE THREAD

**Issue by seveneightNEIN** [Sandrem/FlyCasual#2943]
![garven dreis bug](https://user-images.githubusercontent.com/72008704/94404988-28f45c00-0170-11eb-9009-35885ee1a2af.png)

Hi, I realised that Garven Dreis needs another flyer nearby to activate his skill. if there is no other flyer neaby, the game is stuck. You have to exit to desktop.

**Comment by Benitorathegreat** [comment]
Even with a friendly flyer nearby, his bonus focus action make the game "freeze". I can still move the mouse around but clicking everywhere doesn't resolve anything.

**Comment by Benitorathegreat** [comment]
![focus_crash](https://user-images.githubusercontent.com/9217597/98283756-1985e100-1f6e-11eb-804f-c1c8a5b5024f.png)

**Comment by Neotrail** [comment]
I have the same issue with Garven.
When the dice box are up and you, as Garven use focus and have no eligible friendy in you fire arc.
Then you can't click skip button as the dice box's right column (where you click focus, target lock, evade and so on...) overlaps the button.

Possible sollution:
Move Skip button or reduce the size of the dice box's right column so that the skipbutton can be clicked.

![Garven](https://user-images.githubusercontent.com/74384552/99735097-471d6f00-2ac4-11eb-8497-6dfa2a7109d2.jpg)

**Comment by Sandrem** [comment]
Fixed
