### ISSUE TITLE
Cards not loading

### ISSUE THREAD

**Issue by byrontheii** [Sandrem/FlyCasual#3093]
v1.7.1, Windows 10 machine. When setting up a Rebel squad, clicking on most ship types results in a "Loading..." screen that seems to never finish. In some cases, clicking on the Info button and then going back to the pilot selection screen results in only one pilot being available. Clicking on the Imperial faction New Ship results in a long "Loading..." screen, but ships appeared after several minutes. Clicking on Scum and Villainy New Ship results in a "Loading..." screen for several minutes. After going back and retrying, it eventually displayed the ship names with no pictures; clicking a ship from there resulted in another "Loading..." screen. All other factions' New Ship button resulted in a "Loading..." screen that I didn't wait for. When playing a game with X wings, "Select Side of Dual Card" takes several minutes to display the card sides, and when it finally does they are blank. App CPU usage is between 0.0% and 0.5% during unit selection and between 5-6% during game play, with disk and network at 0 usage.

**Comment by Sandrem** [comment]
The game downloads images from web, such behavior can be caused by problems with Internet connection or if some antivirus/firewall software blocks the game.

Also, you can delete cached images - maybe something was corrupted during download. Path for cached images: "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual\Second Edition\ImageCache"

**Comment by byrontheii** [comment]
Resolved by opening ports in firewall for VPN connections. Thanks for the helpful clues!
