### ISSUE TITLE
Underslung Blaster Cannon upgrade not working on T-70 X-wing Resistance

### ISSUE THREAD

**Issue by Shaddowalker** [Sandrem/FlyCasual#3176]
The Underslung Blaster Cannon (hereafter UBC) is not completing the steps needed to attack.  It does prompt correctly asking if you want to use it Yes/No when the correct situation arises (Enemy completes a maneuver in range 1 of the turret Arc).  
After you choose Yes and attempt to pick the target an error message shows in the red information banner.  (images attached)

My first encounter was with the turret facing in the front Arc.  The message stated that I could not attempt to fire with the Primary Weapon, that I must use the UBC.

I then repositioned all my turrets to see if the Primary Weapon in the same Arc was the cause.  When the next ship flew into range 1 of the side turret facing the prompt again appeared.  Do you want to use the UBC?  I chose Yes.  Then a different message appeared stating that the target was not valid.

Hypothesis:  When the UBC goes to fire, it is attempting to use the Primary Weapon and not the UBC upgrade.  This explains why the error stated I could not fire the Primary weapon in the front Arc.   And why it stated the ship was not a legal target when it was not in the primary firing Arc.  In the side Arc attempt, it was still trying to use the Primary weapon but the message was different because the target was not located in the Primary Weapon Arc.

After typing this message I cannot figure out how to add the images.
![Underslung Blaster Cannon does not fire a](https://user-images.githubusercontent.com/79438340/108669396-95b31e80-74a2-11eb-87f2-0de8b533d939.jpg)
![Underslung Blaster Cannon does not fire b](https://user-images.githubusercontent.com/79438340/108669397-964bb500-74a2-11eb-848c-7135f7e6de7d.jpg)
![Underslung Blaster Cannon does not fire c](https://user-images.githubusercontent.com/79438340/108669398-964bb500-74a2-11eb-8320-4cf2c187046e.jpg)

Best Regards,
Shaddowalker

**Comment by missileaway** [comment]
Underslung blaster cannon requires you to have a lock on the target in order to be fired. In the screenshots it appears that you don't have a lock on any of the opposing ships, which would make them invalid targets. However, Underslung should not be prompting the attack if the target is not locked. 

Underslung blaster cannon: 

After an enemy ship executes a maneuver, you may perform this attack against it as a bonus attack.

Attack (LOCK): Your dice can be modified only by spending a lock for the default effect.
