### ISSUE TITLE
Error when ai activates merciless pursuit 

### ISSUE THREAD

**Issue by STONEHANDS33** [Sandrem/FlyCasual#3339]
![Screenshot_20210911-092422_Fly Casual](https://user-images.githubusercontent.com/68164759/132949400-890a0948-50d2-4758-9894-0c69521600d5.jpg)

**Comment by achapin** [comment]
I had this crash as well. Luke Skywalker fired protorps at The Mandalorian (+ the child). Didn't have to spend his lock. After the attack, this bug happened.

Also, the Child on Dash Rendar!? You are an evil person 😆

**Comment by achapin** [comment]
I started looking through the code to figure out what's going on - it seems like the Combat object has been cleared by the time the SubPhase is being resolved.

![childissue](https://user-images.githubusercontent.com/4753012/143660723-80f21b85-fe5a-417d-8ae6-ffef026f2fe2.png)

So far, I tried:
1. Just caching the Attacker and Defender. That seems to work, but after the AI gets the target lock assigned, the game does not progress. It's still running, but it seems stuck. 
2. I also tried the above approach, but with also moving the ConfirmDecision call to after the lock is assigned. That caused a NullRef in the subphase handling.
3. Tried to replicate the flow used by Magva Yarro, but since that card is an ability and this is a condition, the execution environment isn't similar.

I'll keep plugging away at it if I have more time, just leaving these notes here in case someone else gets to it first.
