### ISSUE TITLE
Export only exports rebel list

### ISSUE THREAD

**Issue by Heilemann** [Sandrem/FlyCasual#467]
Either I can't figure out how to use this thing, or export only ever lists the rebel side of the lists.

**Comment by SteveB526** [comment]
I think whatever you want too export has to be on the left side. Change
your faction on the left to empire, build your list and then export.

On Jan 13, 2018 6:34 PM, "Michael Heilemann" <notifications@github.com>
wrote:

Either I can't figure out how to use this thing, or export only ever lists
the rebel side of the lists.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sandrem/FlyCasual/issues/467>, or mute the thread

**Comment by Heilemann** [comment]
Ah, that's very much not clear from the UI.

So if that's the case for import as well, how would I import two lists to play against one another (with AI).

**Comment by Sandrem** [comment]
Squad builder in version 0.3.2 has support of Import/Export only for Player 1 (left list).
Soon version 0.4.0 will be released with new Squad Builder and better support of Import/Export
https://www.youtube.com/watch?v=wWMWvfp9zIc
