### ISSUE TITLE
0.42 TLT doesn't work as expected.

### ISSUE THREAD

**Issue by FMJFirebird** [Sandrem/FlyCasual#662]
I used a TIE aggressor with TLT. First time I shot outside my firing arc, everthing works as expected. In another round, the TLT won't fire because my target was not in the firing arc (WTF?!).

I made two screenshots: First one shows the error message. In the other screenshot, I fire at another target in the arc. Maybe there is reason for the problem: The primary weapon is listed first. Can it be that the arc validation will be done only for the first weapon? Just a suggestion....
![tlt1](https://user-images.githubusercontent.com/36896583/36746155-e0ea8bc0-1bf1-11e8-96ae-a26107edf255.png)
![tlt2](https://user-images.githubusercontent.com/36896583/36746169-e87caef4-1bf1-11e8-8889-1f71acd655fc.png)

**Comment by Sandrem** [comment]
Hello. Thank you for screenshot.
As you can see, range of shot on first image is 1, but TLT is only fire at range 2-3.
So ship has only 1 weapon that can shoot at range 1 - primary. So no "select weapon" window was shown and attack was checked only for primary weapon.
Not a bug.

I plan to improve way to measure range/in-arc before shot. At the moment you can perfrom this check using right mouse button instead of attack by left mouse button.

**Comment by FMJFirebird** [comment]
Ahhhh. Yes, I forget to think about the range of TLT. Sorry for that. 
The first time, I heard about this project was 2 days ago and I'm very impressed about this good work. Please keep on!
