### ISSUE TITLE
Linux version wont run

### ISSUE THREAD

**Issue by tehpenguin** [Sandrem/FlyCasual#700]
I have downloaded and extracted linux.zip in Ubuntu 16.04. I made FlyCasual.x86 executable. I tried running it by right clicking it and clicking run. I tried double clicking it. I tried to start it with ./FlyCasual.x86. Am I doing something wrong?

**Comment by Sandrem** [comment]
I googled this for you: https://askubuntu.com/questions/223228/how-do-i-run-a-game-with-a-x86-extension
If this doesn't help, try to google for another solutions.

**Comment by tehpenguin** [comment]
Those are the steps I already took from that same thread.

**Comment by tehpenguin** [comment]
Why is this thread closed? Maybe others know what to do.

**Comment by Sandrem** [comment]
Issues are needed to let to know developers that bugs are present and help to fix them. This is not a bug.

You ask the question on a wrong site. I can help only if problem is inside the game files. If you have problems with opening a file in Linux - this question should be asked on Linux-related forum. My skills in Linux are at total-noob-level, so only way how I can help you is to google this instead of you (instead of developement of new sweet feature of real bugfixing).

If there are some things that players need to know - then this is a task for FAQ or WIKI, not for a bug-tracker for developers. For example, I already got ~10 reports "Ship cannot attack with TLT" where on screenshot distance 1 is shown - but this is not a reason to leave such issue open for another "TLT bug reporters".

**Comment by tehpenguin** [comment]
It turns out that 32 bit binaries are needed in order for it to work.

**Comment by Sandrem** [comment]
Thank you, I will inform another players about this solution, if such problems will be reported again.

**Comment by tehpenguin** [comment]
I can create an installation guide and submit it if you would like

**Comment by Sandrem** [comment]
Great, this will be useful - I can add it to project's wiki.

**Comment by nickell-andrew** [comment]
@tehpenguin did you ever finish that installation guide?
