### ISSUE TITLE
Virus Scanner Issue

### ISSUE THREAD

**Issue by Nniol** [Sandrem/FlyCasual#712]
When I try and run the Windows executable my Virus Scanner says the my is not from a reputable source and deletes the file.
![image](https://user-images.githubusercontent.com/1842296/37196188-28e48616-2376-11e8-8de5-f700499dce26.png)

**Comment by Sandrem** [comment]
This is known problem. "Bad reputation" false detection is shown because file is too new, and installed on small amount of computers. I, as a developer, don't have strong reputation or certificates  like Microsoft) This is an issue with free antiviruses, like Avira and AVG. You can upload exe file to virustotal.com to check that it is safe.

**Comment by Sandrem** [comment]
By the way, what antivirus do you use?

**Comment by Nniol** [comment]
I am using Symantec Endpoint Protection.

I understand the issue and assume that the file is safe, but I can't get
round the protection.

This was just a heads up for you

**Comment by Sandrem** [comment]
You can add file to list of exceptions, if you can.
Or wait until it will be popular enough that antivirus turns off "bad reputation" warning.
