### ISSUE TITLE
HOTAC AI

### ISSUE THREAD

**Issue by Chaotix** [Sandrem/FlyCasual#747]
I noticed that the AI doesn't take its second attack.  ever.  It states that it can in the notification, but then the turn goes to the next ship.

**Comment by Sandrem** [comment]
This feature is not implemented yet.
There are few rules/ability that prevents AI from attacking any target they want (Biggs, for example), so I decided to add support of second attacks for AI later, to evade possible bugs.

I will close this issue, because this is not a bug, but unfinished feature. It is planned for one of the next updates.
