### ISSUE TITLE
Multiplayer doesn't work.

### ISSUE THREAD

**Issue by Chicken492** [Sandrem/FlyCasual#933]
Me and a friend are attempting to play together but whenever one of us host a game it either doesn't show up, or it does but won't load the joiner into the game.

**Comment by Sandrem** [comment]
Are you from the same region, or different ones (for example, USA and Europe) ?

**Comment by Chicken492** [comment]
We both live in the same region.

**Comment by Sandrem** [comment]
As I know, Unity uses few matchmaking servers, so players from different regions don't see each other because use different servers. I don't know why you got the same problem in one region (maybe, issue with Internet providers?).
I plan to use a single matchmaking server for all regions in 0.5.0
Please, reopen issue if you will have the same problem after release of 0.5.0

Also, check versions of the game - if they are different, you will not see each other.
